### ISSUE TITLE
Book_1_Ch_21 page 14 图片标注错误

### ISSUE THREAD

**Issue by KangjunWu** [Visualize-ML/Book1_Python-For-Beginners#102]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/133469901/74bc11d2-87c8-46ab-a7e6-3865717f77ce)

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了，这个issue先开着，十一月我统一修改。请继续批评指正
