### ISSUE TITLE
Book_1/Book_1_Ch_26__SciPy page12

### ISSUE THREAD

**Issue by 521haohaoxuexi123** [Visualize-ML/Book1_Python-For-Beginners#104]
'nearest' 代表最近邻插值。如图 7 (d) 所示，应该是如图 7 (f) 所示;
'previous' 代表前向插值。如图 7 (e) 所示,应该是如图 7 (d) 所示;
'next' 代表后向插值。如图 7 (f) 所示，应该是如图 7 (e) 所示;

**Comment by Visualize-ML** [comment]
谢谢你！确实写错了，这个issue先开着。我会在排版稿上修改。请继续批评指正。

Cheers
