### ISSUE TITLE
Book1_Ch3_表8

### ISSUE THREAD

**Issue by ZiyuLin-DASHi** [Visualize-ML/Book1_Python-For-Beginners#113]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/5f9eb493-fb71-47a4-ad79-e27fbb6bb506)
这个地方前面两个框里用的是"i"，后面用的是"n"，可能需要统一一下。

**Comment by Visualize-ML** [comment]
谢谢你，确实需要统一，十二月份统一修改。请继续批评指正。
