### ISSUE TITLE
ch11 代码14 

### ISSUE THREAD

**Issue by yueye231300** [Visualize-ML/Book1_Python-For-Beginners#115]
quiver函数输入参数arrow_length_ratio=0时，不会给出合适的箭头大小，箭头的大小为0，需要自己调整参数，才会出现不同大小的箭头
<img width="372" alt="Snipaste_2023-12-03_19-12-00" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/124552231/c14bc269-660c-4897-8d4e-f24b8721a953">
改变值为0.03出现较为合理的箭头大小
<img width="450" alt="change" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/124552231/565868a1-8034-48b6-ad69-4a492640820b">

**Comment by Visualize-ML** [comment]
谢谢你，会在十二月中集中修改。请继续批评指正。

Cheers
