### ISSUE TITLE
Bk1_Ch12_01 代码错误

### ISSUE THREAD

**Issue by yueye231300** [Visualize-ML/Book1_Python-For-Beginners#118]
在绘制箱型图时，如果要考虑鸢尾花种类，还要对不同种类的颜色进行上色，应该使用hue=‘species'参数，这里似乎缺少了这个参数
<img width="654" alt="Snipaste_2023-12-05_09-57-18" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/124552231/3403e6d4-b27a-4cee-8e5f-f3d7cd8293ef">
添加参数之后与书中变得一样
<img width="679" alt="change" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/124552231/145e27f8-ca69-4f66-97bd-08ab74df6a8b">

**Comment by yueye231300** [comment]
同一本书中的代码7，在绘制的时候也出现了相同的问题，缺少了这个参数，但是我看作者一开始的代码中的结果时正确的，但我自己跑却没有相同的颜色，不知道为什么，希望作者可以解答我的疑惑

**Comment by Visualize-ML** [comment]
谢谢你的反馈，我十二月中要查一遍这些问题。也请继续批评指正。
