### ISSUE TITLE
Book_1_Ch_13__聊聊NumPy-Page5 13.3生成数列

### ISSUE THREAD

**Issue by linjunhua1** [Visualize-ML/Book1_Python-For-Beginners#12]
numpy.linspace(start, stop, num, endpoint)。生成等间距数列，从起始值 start 开始，到结束值
stop 结束，num 指定数列的长度 (元素的个数)，默认为 50。endpoint 参数指定是否包含结束
值。例如，numpy.linspace(1, 10, 6) 生成一个等间距数列 **[1, 3.25, 5.5, 7.75, 10]。**
修改为**[ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ] **

**Comment by Visualize-ML** [comment]
谢谢你！请继续纠错，六月中统一修改。

Cheers,
James
