### ISSUE TITLE
Book_1_Ch_06 区间建议

### ISSUE THREAD

**Issue by Mephistofer** [Visualize-ML/Book1_Python-For-Beginners#121]
Book_1_Ch_06第24页
“用列表生成式和 random.uniform() 产生在区间 [0, 10) 内均匀分布的 50 个随机数。”
这里的 random.uniform() 产生的应该是闭区间中的数据，即[0,10]。

**Comment by Visualize-ML** [comment]
谢谢你，确实是闭区间。会在十二月中旬集中修改，请继续批评指正。

Cheers,
James
