### ISSUE TITLE
Book1_Ch4_Page13图片缺失文字

### ISSUE THREAD

**Issue by LunFengChen** [Visualize-ML/Book1_Python-For-Beginners#133]
字符串分解漏了“n"
![Snipaste_2023-12-26_13-47-37](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/108616973/4755ce59-5aa2-4ff6-940a-21d48d70c220)

**Comment by Visualize-ML** [comment]
谢谢你，下个月统一修改
