### ISSUE TITLE
Book1_ch07

### ISSUE THREAD

**Issue by ZiyuLin-DASHi** [Visualize-ML/Book1_Python-For-Beginners#134]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/54adcde3-bf16-407d-b896-85f9b35ee3e3)
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/962cd5b7-1cb9-46f3-a5f6-82adafa8146c)

代码21不在ipynb文件中

**Comment by Visualize-ML** [comment]
谢谢你，我查一下，一月份补齐。请继续批评指正。

**Comment by ZiyuLin-DASHi** [comment]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/d6bbae1e-f177-4cc6-b9bf-38cf84dce3cf)
在e处，global_x输出应该是8，因为这里还没有声明全局变量

**Comment by ZiyuLin-DASHi** [comment]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/c6f96b22-eed0-4b28-923c-71f1e60adbdf)
**ch09**中，g：计算两个方差；第一个方差相当于**粽子方差**
这里应该打错了，应是**总体方差**

**Comment by ZiyuLin-DASHi** [comment]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/c41eda0f-6cf7-4841-9ffa-b1e9540c73b5)
ch09, Page8：不同于self，类方法的第一个参数通常被命名为cls，它表示类本身**而不是实例简单来说**，cls 是一个约定俗成的名字
这里粗体字中，“简单来说”前面少了一个标点符号

**Comment by Visualize-ML** [comment]
谢谢你，要等到二月初统一修改了。请继续批评指正。

**Comment by ZiyuLin-DASHi** [comment]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/755039a5-ec4f-4b89-ada8-595da0c24f29)
这个地方写反了，a应该是相关系数矩阵，b应该是协方差矩阵

**Comment by ZiyuLin-DASHi** [comment]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/bf629020-e85d-4326-99ba-b88d83c491f4)
红框处有错误，结果应该如下图
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/118437496/edadf4a3-8e77-4fb3-ae43-0cd09422d444)

**Comment by Visualize-ML** [comment]
这个确实画错了，少画了一行。这些错误请先开着，我会集中修改。请继续批评指正。
