### ISSUE TITLE
Book1_ch30.2 一处错误

### ISSUE THREAD

**Issue by blue1018** [Visualize-ML/Book1_Python-For-Beginners#135]
![微信图片_20231229191058](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/17232965/b33cbc7a-e49b-4493-98ec-69466e84c9b8)

第一次发现错误好兴奋呀，好像是送书呢？

**Comment by Visualize-ML** [comment]
谢谢你！

是的，鸢尾花书纠错赠书 + 签名卡。纠错数量排名前十的同学会得奖。请继续批评指正。
