### ISSUE TITLE
Book1_ch31.4 一 图片下面的文字 ”排版时，请尽量不要缩放此图“

### ISSUE THREAD

**Issue by blue1018** [Visualize-ML/Book1_Python-For-Beginners#137]
![微信图片_20240102181444](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/17232965/017cb745-ddfa-4b17-9402-1b805391bd53)

 ”排版时，请尽量不要缩放此图“，不用去掉吗，着一页有好几张都带。这种提示放注释里好点吧。

**Comment by Visualize-ML** [comment]
谢谢你，这是给排版老师看的。
