### ISSUE TITLE
Book1_Ch05_Python数据结构 

### ISSUE THREAD

**Issue by Violetbit** [Visualize-ML/Book1_Python-For-Beginners#139]
从Seaborn导入鸢尾花数据集这个代码我运行不了
![Uploading 微信图片_20240111122345.png…]()

**Comment by Violetbit** [comment]
iris_df = sns.load_dataset("iris")
# 使用seaborn.load_dataset函数加载Iris数据集
iris_df = sns.load_dataset("iris")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], line 2
      1 # 使用seaborn.load_dataset函数加载Iris数据集
----> 2 iris_df = sns.load_dataset("iris")

File ~\anaconda3\Lib\site-packages\seaborn\utils.py:587, in load_dataset(name, cache, data_home, **kws)
    585 if not os.path.exists(cache_path):
    586     if name not in get_dataset_names():
--> 587         raise ValueError(f"'{name}' is not one of the example datasets.")
    588     urlretrieve(url, cache_path)
    589 full_path = cache_path

ValueError: 'iris' is not one of the example datasets.

**Comment by Visualize-ML** [comment]
重新装一下seaborn
或者，从scikit learn或plotly加载鸢尾花数据集

**Comment by Violetbit** [comment]
重装seaborn的方法失败，从scikit learn中导入成功但是iris.head()运行失败。从seaborn中导入的iris和scikit learn中导入的iris好像数据类型不一样

**Comment by Visualize-ML** [comment]
scikit learn特征数据是NumPy Array. 你再试试plotly导入

**Comment by Violetbit** [comment]
成功了，感谢

**Comment by Violetbit** [comment]
Book1_Ch07第7页isdigit()只对0和正整数有效，文章中表述“使用isdigit的方法检查输入是否是一个数值”存在问题

**Comment by Visualize-ML** [comment]
谢谢你，请继续批评指正。这个issue先开着，二月份修改。
