### ISSUE TITLE
Book_1_Ch_01__聊聊巨蟒__编程不难-Page5-语言表述的问题

### ISSUE THREAD

**Issue by herwhiskers** [Visualize-ML/Book1_Python-For-Beginners#14]
最后一段中“这是学 Python 必须避免”为病句，可以改成“这是学 Python 所必须避免的”。

另外，原段落是这样：

> 大家学 Python 时，一定要吸取英语教育的教训。（_很多人_）学了十几年的哑巴英语，原因就是只关注词汇、语法、应试，而不是利用语言进行口头、书面交流。这是学 Python 必须避免。（_我_）建议大家在学 Python 编程的时候，一定要抱着极强的“功利心 ”——立刻开始 coding、debugging！

感觉主语有点杂糅（省略主语的情况下又换了主语），可能换一换表达会更流畅。比如：

> 在学习 Python 的过程中，大家一定要吸取英语教育的教训。很多人之所以在学了十几年的英语之后仍然不会说，就是因为他们只注重词汇、语法和应试，而没有真正把语言用起来，进行口头和书面交流。前车可鉴，在学习 Python 时，大家不妨“功利”一些，边学边练——在学习中就马上开始编码和调试（coding 和 debugging）。

**Comment by Visualize-ML** [comment]
请继续批评，Book1的问题，草稿全部上传后统一修改
