### ISSUE TITLE
Book_1_Ch_15 图片顺序错误

### ISSUE THREAD

**Issue by Stanley2Data** [Visualize-ML/Book1_Python-For-Beginners#141]
<img width="809" alt="Snipaste_2024-01-17_19-24-57" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/134713032/49f6ca23-e9b9-49ec-996e-0b75f97a0831">
P8 图11 协方差矩阵和相关性系数矩阵的图顺序反了

**Comment by Visualize-ML** [comment]
谢谢，二月统一修改。请继续批评指正。
