### ISSUE TITLE
Book_1_Ch_06 '频率'建议修改为‘频数'

### ISSUE THREAD

**Issue by BUAAerKOH** [Visualize-ML/Book1_Python-For-Beginners#142]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/151934096/cfa05714-fbaa-4c29-b76f-9f175bac62fd)
21页底部
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/151934096/5f0c5745-c760-4a09-ac1b-0c31bebe1093)
22页注释h下density设置为False，纵轴表示频数而非频率

**Comment by Visualize-ML** [comment]
谢谢你！请继续批评指正！后续会在纸质书上修改。

Cheers,
James
