### ISSUE TITLE
Book_1_Ch_00__正文前__编程不难__鸢尾花书__从加减乘除到机器学习

### ISSUE THREAD

**Issue by cokas** [Visualize-ML/Book1_Python-For-Beginners#144]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/30469333/2e7452b5-5336-4c6c-8534-f739ea3cd3ce)
这句话中是不是想表达“不是···· ····而是”？
原句：          配套的 Jupyter Notebook 不是可有可无，而且《编程不难》学习生态关键一环。
我理解的：   配套的 Jupyter Notebook 不是可有可无，**而是**《编程不难》学习生态**的**关键一环。】

**Comment by Visualize-ML** [comment]
谢谢你，确实笔误！也请你继续批评指正。

Cheers
