### ISSUE TITLE
ch01_page24

### ISSUE THREAD

**Issue by Liltomato1998** [Visualize-ML/Book1_Python-For-Beginners#145]
<img width="242" alt="屏幕截图 2024-02-29 211237" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/74699281/a5de82ab-b377-498d-865d-b2a0b5d4d6d4">

第一章24页回归脑图这里两个基于降维是刻意分开的吗

**Comment by Visualize-ML** [comment]
写错了，请继续批评指正。
