### ISSUE TITLE
wrong words

### ISSUE THREAD

**Issue by hcyhh** [Visualize-ML/Book1_Python-For-Beginners#147]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/115518961/e03885e6-2263-4ef7-8e24-014a481213eb)

**Comment by Visualize-ML** [comment]
谢谢，确实写错

**Comment by hcyhh** [comment]
wow! 加油👏

---- Replied Message ----
| From | Iris Series: Visualize Math -- From Arithmetic Basics to Machine ***@***.***> |
| Date | 03/15/2024 22:27 |
| To | Visualize-ML/Book1_Python-For-Beginners ***@***.***> |
| Cc | hcyhh ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Visualize-ML/Book1_Python-For-Beginners] wrong words (Issue #147) |

谢谢，确实写错
