### ISSUE TITLE
Book_1_Ch_02__JupyterLab__编程不难-Page6-表1快捷键错误

### ISSUE THREAD

**Issue by asdChenJin** [Visualize-ML/Book1_Python-For-Beginners#15]
![图片1](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/33625968/3e7e3547-39e6-41d6-a56d-cabb15cbaf4b)

表1.编辑模式，常用快捷键里面的快捷键组合：Crtl + [ 和Crtl + ] 的功能写反了

**Comment by Visualize-ML** [comment]
请多提意见，后续统一修改。谢谢

**Comment by Visualize-ML** [comment]
谢谢支持，请多多批评。第一本书一共36章，还在慢慢填坑
