### ISSUE TITLE
Book_1_Ch_11 P25 & P26 可能是多字

### ISSUE THREAD

**Issue by try2love** [Visualize-ML/Book1_Python-For-Beginners#151]
bk1_ch11，11.6三维散点一节，P25中matplotlib绘图的注释中为“图 16. 用 Matplotlib **和**绘制三维散点图” 与P26中代码cell下的标注“代码 8. 用 Matplotlib **和**绘制三维散点图”
这两个句子里面似乎“和”字是多余的。

**Comment by Visualize-ML** [comment]
谢谢你，确实多字，会在排版稿修改，请继续批评指正。
