### ISSUE TITLE
tiny typo

### ISSUE THREAD

**Issue by shenhai-ran** [Visualize-ML/Book1_Python-For-Beginners#154]
1. chapter 7, page 18, the line below the first graph, numpy.arra`y`(), missing a `y` :)
2.  code block 21 is not in `Bk1_Ch07_17.ipynb`, and `stop_time = time.time()` is missing for the second time calculation.

**Comment by Visualize-ML** [comment]
谢谢你，确实有问题。请继续批评指正。
