### ISSUE TITLE
Book_1_Ch_19代码问题

### ISSUE THREAD

**Issue by tnsongs** [Visualize-ML/Book1_Python-For-Beginners#155]
DataFrame中没有iteritems()，应该是items()。

![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/39915148/a067e20d-5f3c-4b1b-bcf0-e02b793bc555)

**Comment by Visualize-ML** [comment]
谢谢你，确实在未来版本这个方法会失效。

https://pandas.pydata.org/pandas-docs/version/1.3/reference/api/pandas.DataFrame.iteritems.html
