### ISSUE TITLE
Bk1_Ch3_01.ipynb的1.2 生成二元函数数据 chatgpt的解释有误

### ISSUE THREAD

**Issue by xxovo123** [Visualize-ML/Book1_Python-For-Beginners#159]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/76762095/7e4598a1-a976-4a90-86e4-d48bbd5b7a17)
chatgpt 解释称# 即矩阵中的每个元素 (i,j) 都满足 xx1[i,j]=x1_array[i]，xx2[i,j]=x2_array[j]。
但是实际上xx1, xx2 = np.meshgrid(x1_array, x2_array) 应该的解释应该是生成两个二维矩阵，第一个矩阵满足每一行都是x1_array，且有x2_array.size行，第二个矩阵满足每一列都是x2_array，且有x1_array.size列
举个很简单的例子
![捕获](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/76762095/f1e8bd83-6d88-44a7-93d6-2564bd0b24f0)
我们可以看到X[2,0]==x[2]是不满足的
所以正确的解释应该是
即矩阵中的每个元素 (i,j) 都满足 xx1[i,j]=x1_array[j]，xx2[i,j]=x2_array[i]。

**Comment by Visualize-ML** [comment]
确实不准确，请继续批评指正。谢谢。
