### ISSUE TITLE
Book_1_Ch_08__Python函数__编程不难-Page2-说半句话

### ISSUE THREAD

**Issue by asdChenJin** [Visualize-ML/Book1_Python-For-Beginners#16]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/33625968/3ea43023-44f1-4d17-a3d6-231c5e5bc7ad)
此处应为`list()可以将输入的可迭代对象转为list数据类型。`

**Comment by Visualize-ML** [comment]
谢谢你！请继续纠错，六月中统一修改。

Cheers,
James
