### ISSUE TITLE
Book_1_Ch_31__Scikit-Learn子标题有误

### ISSUE THREAD

**Issue by grylics** [Visualize-ML/Book1_Python-For-Beginners#160]
Book_1_Ch_31__Scikit-Learn降维里的小标题有误, 出现了两个31.2, 其中   "31.2 两特征PCA"  应该改为   "31.3 两特征PCA"

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改。请继续批评指正。

Cheers
