### ISSUE TITLE
Book1_python-For-Beginners纸质版第三章第47页似乎有些小问题

### ISSUE THREAD

**Issue by autsteve** [Visualize-ML/Book1_Python-For-Beginners#161]
魔法命令一节：

一个百分号 (%) 开头的叫行魔法命令 (line magic)，是只针对当前行生效的方法；两个百分号 (%%) 开头的叫单元格魔法 (cell magic)，对当前整个代码输入框 cell 生效。

为保持翻译一致， **行魔法命令 (line magic)** 是否应直接改为**行魔法 (line magic)**

**Comment by Visualize-ML** [comment]
谢谢你，确实有必要对齐翻译。请继续批评指正。

Cheers,
