### ISSUE TITLE
Book_1_Ch_6__python常见运算 常见运算符里面的小错误

### ISSUE THREAD

**Issue by omae11** [Visualize-ML/Book1_Python-For-Beginners#166]
github不太稳定，老是上不去，不知道能不能传成功，书里面p103页，图6.1里面的常见运算好像没写位运算（bitwise operator），但是图6.1里面有，图中的“-”是不是错了，或运算是竖线|吧？小的才疏学浅，刚学，没见过“-”是啥，所以斗胆问一下
![Uploading image.png…]()

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。请继续批评指正。
