### ISSUE TITLE
Book_1_Ch_05__Python数据类型__编程不难__鸢尾花书__从加减乘除到机器学习.pdf第七页有叙述错误

### ISSUE THREAD

**Issue by fengyuzheHQ** [Visualize-ML/Book1_Python-For-Beginners#167]
在第七页中原文为“除了这些特殊数值外，Math 模块还提供了许多其他数学函数，**比如四舍五入 round()**”，然而round函数为Python内置函数，无需使用math模块，例如若使用print(math.round(4.5)),会有AttributeError                            Traceback (most recent call last)错误
初学Python，如有叙述错误之处，请您见谅。

**Comment by Visualize-ML** [comment]
谢谢你，这一点已经在纸质书中修改，草稿没有同步。请继续批评指正。
