### ISSUE TITLE
Python语言中除了:=其它赋值并不是运算符

### ISSUE THREAD

**Issue by fredxxj** [Visualize-ML/Book1_Python-For-Beginners#168]
普通的赋值=或者类似+=这些在Python当中都是语句，不是运算符

比较常见的错误，但不应该犯。

见官方文档，Python运算符只有

+       -       *       **      /       //      %      @
<<      >>      &       |       ^       ~       :=
<       >       <=      >=      ==      !=

**Comment by Visualize-ML** [comment]
谢谢你，你是对的；这部分应该说清楚。请继续批评指正。
