### ISSUE TITLE
Page19中 自然数集合和整数集合的LaTex表示是否正确？

### ISSUE THREAD

**Issue by canghaiyishengxiao2018** [Visualize-ML/Book1_Python-For-Beginners#169]
用表3.11中的自然数集合和整数集合的LaTex表示（$\N$和$\Z$），在Jupyterlab中Ctrl+Enter后显示为\N和\Z,而不是书所说的符号。

**Comment by canghaiyishengxiao2018** [comment]
今天终于试出来了，自然数集合应该用$\mathbb{N}$，整数集合应该用$\mathbb{Z}$表示才能出现表3.11中的数学符号。

**Comment by Visualize-ML** [comment]
是的，不同版本IDE渲染不同，你建议的语句是最安全的；请继续批评指正。
