### ISSUE TITLE
Ch8 Page2 字不全

### ISSUE THREAD

**Issue by lrh683** [Visualize-ML/Book1_Python-For-Beginners#17]
<img width="909" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/12770293/7f452143-693c-4ebc-bb72-2f3d034bdeab">

list 可以将?

**Comment by Visualize-ML** [comment]
谢谢你，确实写漏掉了。请继续批评指正。

Cheers,
James
