### ISSUE TITLE
纸质书第94页Chapter 5 Python数据类型元组部分第二段叙述有误

### ISSUE THREAD

**Issue by canghaiyishengxiao2018** [Visualize-ML/Book1_Python-For-Beginners#170]
原文“tuple和list都是序列类型，可以存储多个元素，它们都可以通过索引访问**和修改**元素，支持切片操作。”，应该将“和修改”去掉，因为元组元素是不可以修改的。这一点在下一段也有说明。
PDF版在这部分也存在同样的问题。

**Comment by Visualize-ML** [comment]
谢谢你，确实有误。请继续批评指正。
