### ISSUE TITLE
文字错误 Book_1_Ch_03__JupyterLab，用起来__编程不难__鸢尾花书__从加减乘除到机器学习 

### ISSUE THREAD

**Issue by wanghaozi** [Visualize-ML/Book1_Python-For-Beginners#171]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/3345899/c823a4a6-61ad-4d78-a01b-274851be49c5)
 这里应该是进入"命令模式"后 dd 删除 不是"编辑模式"

**Comment by wanghaozi** [comment]
还有就是了解纠错的话 我不知道是只能在issues里面还是有别的途径

**Comment by wanghaozi** [comment]
重启 kernel；在按下 esc 进入编辑模式后，连续按两下零 0，重启 kernel 
也是同样的问题 应该是命令模式 这段比较绕 感觉

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了！请继续批评指正。开issue很好，一个issue，一个问题。纠错多的读者，赠书感谢
