### ISSUE TITLE
Ch08 代码6: # 在函数外部访问全局变量 print("global_x:", global_x) # global_x: 88

### ISSUE THREAD

**Issue by yangkeping** [Visualize-ML/Book1_Python-For-Beginners#174]
Ch08 代码6: # 在函数外部访问全局变量 print("global_x:", global_x) # global_x: 88

I think 88 should be 8.

**Comment by canghaiyishengxiao2018** [comment]
You are right,the paper book has been corrected。

**Comment by Visualize-ML** [comment]
谢谢你，纸质书确实已经修改。请继续批评指正。
