### ISSUE TITLE
Book_1_Ch_03__JupyterLab Page12 键盘上常用按键中英文名称

### ISSUE THREAD

**Issue by JingjieSong** [Visualize-ML/Book1_Python-For-Beginners#177]
<img width="415" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/10057194/5606485a-7f32-4551-bb29-4a3bfbb922c7">
对应的翻译应该为右圆括号，对应纸质书籍的位置为P51，表3.5

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。请继续批评指正
