### ISSUE TITLE
Bk1_Ch3_01.ipynb的【1.2 生成二元函数数据】节的注释

### ISSUE THREAD

**Issue by bighua** [Visualize-ML/Book1_Python-For-Beginners#179]
即矩阵中的每个元素 (i,j) 都满足 xx1[i,j]=x1_array[i]，xx2[i,j]=x2_array[j]。
是否应该是 
xx1[i,j]=x1_array[j]，xx2[i,j]=x2_array[i]

**Comment by PleaseWakeUpBUAA** [comment]
> 即矩阵中的每个元素 (i,j) 都满足 xx1[i,j]=x1_array[i]，xx2[i,j]=x2_array[j]。 是否应该是 xx1[i,j]=x1_array[j]，xx2[i,j]=x2_array[i]

我觉得你说得对
