### ISSUE TITLE
Book_1_Ch_07__Python控制结构__代码示例错误

### ISSUE THREAD

**Issue by Yjsmall** [Visualize-ML/Book1_Python-For-Beginners#18]
第 9 页这个例子表达的意思错误，这里说使用 zip来实现向量内积，却没有使用。
我猜测是不是应该这样实现：
~~~Python
for x, y in zip(a, b):
    dot_product += x * y
~~~
<img width="801" alt="截屏2023-05-25 19 41 24" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/56305848/25427ac3-16d7-4d5e-8056-96d28854840c">

**Comment by Visualize-ML** [comment]
谢谢你，现在是用来对比的代码，忘了贴zip代码。七月份会统一修改，请继续批评。

Cheers,
James
