### ISSUE TITLE
 Book 1《编程不难》的 Chapter 7 Python 控制结构 pdf 第19 页的代码问题

### ISSUE THREAD

**Issue by pao2ping5** [Visualize-ML/Book1_Python-For-Beginners#181]
![image](https://github.com/user-attachments/assets/ad60aef4-6fb5-4081-904e-f842fbf707b2)
手动计算矩阵乘法，没有结束时间。
![屏幕截图 2024-07-19 165150](https://github.com/user-attachments/assets/af7f76ea-dfc2-44a1-8f43-5847d529b1a3)

**Comment by Visualize-ML** [comment]
谢谢你，确实缺一句话。请继续批评指正。

Cheers
