### ISSUE TITLE
Book_1_Ch_05__Python数据类型__编程不难__鸢尾花书__从加减乘除到机器学习.pdf 第一页的函数名有误

### ISSUE THREAD

**Issue by zero-ship-it** [Visualize-ML/Book1_Python-For-Beginners#182]
![鸢尾花书B1C5P1](https://github.com/user-attachments/assets/3f93635d-b3e9-42dc-94d7-aee6a75a8065)

**Comment by Visualize-ML** [comment]
谢谢你，纸质书已经修改。请继续批评指正。
