### ISSUE TITLE
Book_1_Ch_03__JupyterLab 代码3.2 高亮范围问题

### ISSUE THREAD

**Issue by AnikiFan** [Visualize-ML/Book1_Python-For-Beginners#183]
![Screenshot 2024-07-30 204115](https://github.com/user-attachments/assets/8fc3cce1-b144-421e-9216-ea0804f4e8ad)
最右侧的`\right)`应该对应的是最外层的括号，不应被高亮

**Comment by Visualize-ML** [comment]
谢谢你，确实有问题。
