### ISSUE TITLE
Book_1_Ch_15__NumPy常见运算 2024年5月第一版纸质书错误

### ISSUE THREAD

**Issue by AnikiFan** [Visualize-ML/Book1_Python-For-Beginners#184]
![a6a6af081e4c2de25a325ef0912bf4f](https://github.com/user-attachments/assets/fd73c264-b295-41fa-bd17-40844820a961)
![Screenshot 2024-08-01 094934](https://github.com/user-attachments/assets/0450b61c-4752-4e72-80a7-2c391ab76a87)
电子版对应部分应该是正确的
![1c3263a20df4a9d6cf566d9288330e6](https://github.com/user-attachments/assets/75e27f89-8c93-42ce-94dc-ff4bf3072754)

**Comment by Visualize-ML** [comment]
排版确实出现问题，请继续批评指正。谢谢你。
