### ISSUE TITLE
个人觉得对meshgrid的解释不太清楚，这里有个更清晰的解释：https://stackoverflow.com/a/42404323

### ISSUE THREAD

**Issue by JunYang-tes** [Visualize-ML/Book1_Python-For-Beginners#188]
RT

**Comment by Unclegeek** [comment]
unsubscribe



---- 回复的原邮件 ----
| 发件人 | Yang ***@***.***> |
| 日期 | 2024年08月23日 17:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Visualize-ML/Book1_Python-For-Beginners] 个人觉得对meshgrid的解释不太清楚，这里有个更清晰的解释：https://stackoverflow.com/a/42404323 (Issue #188) |

RT
