### ISSUE TITLE
Book1_Ch09_Page6 代码5与正文有出入

### ISSUE THREAD

**Issue by AwayGithub** [Visualize-ML/Book1_Python-For-Beginners#190]
正文中说“第一个方差相当于粽子方差，第二个方差相当于样本无偏方差”。
但代码中第二个方差ddof为0，第一个方差ddof为1才是样本无偏方差。
此外，我没有搜索到“粽子方差”这个名词。是指ddof=0时的方差吗？
![1](https://github.com/user-attachments/assets/b02a5115-e81b-4717-a2ab-a323ea0bda3e)
![2](https://github.com/user-attachments/assets/d35e7f9b-7fd7-40c3-900a-69618c521a0d)

**Comment by Visualize-ML** [comment]
请麻烦具体说明，谢谢你！

**Comment by AwayGithub** [comment]
不好意思，这里应该没有问题，是我想错了
不过“粽子方差”应为“总体方差的无偏估计”
