### ISSUE TITLE
Book1_Ch11 错别字

### ISSUE THREAD

**Issue by AwayGithub** [Visualize-ML/Book1_Python-For-Beginners#191]
1. Page 3
应为：“都**有**两个坐标值”
![1](https://github.com/user-attachments/assets/effd468a-697f-4a8e-bb0f-544c60232547)

2. Page 5
应为：“也就是第1/2**列**”（？）
![2](https://github.com/user-attachments/assets/3ba86216-2314-45e1-90a4-0936cd73b19d)

3. Page 10
应为：“在平行于$x_1x_2$**的**特定高度切一刀”
![3](https://github.com/user-attachments/assets/d220f1e1-4acf-40e5-811a-de8db7106959)

**Comment by Visualize-ML** [comment]
谢谢你！图片看不到，能再发一遍吗？谢谢

**Comment by AwayGithub** [comment]
现在也不能看到吗？我这边可以显示图片
1. Page 3
原文为：“它由一系列离散的数据点组成，其中每个数据点都**由**两个坐标值。”
应为：“都**有**两个坐标值”

2. Page 5
原文为：“用iris.data[:,0]提取NumPy数组的索引为0列，也就是第1**例**“
或许应为：”也就是第1**列**“（我不太确定）
原文为：“用iris.data[:,1]提取NumPy数组的索引为1列，也就是第2**例**“
或许应为：”也就是第2**列**“（我不太确定）

3. Page 10
原文为：“在平行于x1x2平面**在**特定高度切一刀，得到的轮廓线就是一条等高线。”
应为：“在平行于x1x2平面**的**特定高度切一刀”或“平行于x1x2平面**在**特定高度切一刀”

**Comment by Visualize-ML** [comment]
谢谢你，已经逐一查过，这些问题纸质书都已经修改，电子草稿没有同步。请继续批评指正。
