### ISSUE TITLE
建议调整Cheatsheet_JupyterLab__编程不难__鸢尾花书__从加减乘除到机器学习.pdf中按键顺序

### ISSUE THREAD

**Issue by g-sun** [Visualize-ML/Book1_Python-For-Beginners#2]
我记得其他书和习惯中，一般都是ctrl/alt/shift/tab/enter这样的顺序。
所以建议把shift+ctrl这种，调整成ctrl+shift，以便与习惯一致，谢谢。

**Comment by Visualize-ML** [comment]
谢谢你！这个确实是个问题，后面将调整。欢迎继续批评
