### ISSUE TITLE
PDF 目录

### ISSUE THREAD

**Issue by Iey4iej3** [Visualize-ML/Book1_Python-For-Beginners#23]
这一系列书生成的 PDF 似乎不包含 PDF 目录。编译的时候自动生成目录应该是很直接的（如果是 LaTeX 写，应该就是加上 bookmark 宏包。此外我也不清楚是否加上了 hyperref 宏包，没注意到 PDF 中是否有超链接）。

当然软件编译的 PDF 如果没有经过特殊混淆，自动生成 PDF 目录也不麻烦，例如用 [pdf.tocgen](https://github.com/Krasjet/pdf.tocgen)，只是如果在编译期能自动生成，读者就没必要事后处理了。

**Comment by Visualize-ML** [comment]
谢谢你的建议，这套PDF使用word编写转PDF。目前没有推出合集的计划。

请继续批评指正。

Cheers,
James
