### ISSUE TITLE
CH14 Numpy

### ISSUE THREAD

**Issue by lrh683** [Visualize-ML/Book1_Python-For-Beginners#24]
<img width="716" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/12770293/3b97f29e-ae15-4516-91f7-5a84c0d29bc9">
最后三个元素的取法,似乎有误

**Comment by Visualize-ML** [comment]
确实写错了（复制粘贴惹的祸）！请继续批评，我会在七月份集中修改。谢谢

Cheers,

**Comment by lrh683** [comment]
谢谢你的工作.让我重拾对数学的信心~
