### ISSUE TITLE
Book_1_Ch_04__Python语法，边学边用    语言表述问题

### ISSUE THREAD

**Issue by alexxxxxxy** [Visualize-ML/Book1_Python-For-Beginners#38]
page11，变量赋值第一句话似乎有点问题: "大家都已经起初"——“大家都已经清楚”？

辛苦老师下次一并修改~

（我第一次用GitHub，不知为啥图片上传一直出错TAT）

**Comment by Visualize-ML** [comment]
谢谢你，九月份统一修改，请继续批评。

Cheers,
James
