### ISSUE TITLE
Book_1_Ch_17__NumPy数组规整-Page5-图11

### ISSUE THREAD

**Issue by fre-air** [Visualize-ML/Book1_Python-For-Beginners#39]
![图11](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/75653727/b34d75b7-435e-442d-9c0f-b9b065cbc4ea)
### 图11中，numpy.repeat()图注与图名numpy.tile()不符

**Comment by Visualize-ML** [comment]
谢谢你，九月份统一修改，请继续批评。

Cheers,
James
