### ISSUE TITLE
Book_1_ch_01 1.2python？巨蟒？

### ISSUE THREAD

**Issue by DYK395** [Visualize-ML/Book1_Python-For-Beginners#40]
不是什么大的错误，是表述上有问题，“这就是为什么鸢尾花书系列会选择Python作为编成语言的原因”，应该是“这就是为什么...”或者“这就是...的原因”比较通顺。

**Comment by Visualize-ML** [comment]
谢谢，九月份统一修改。请继续批评指正。

Cheers,
James
