### ISSUE TITLE
Bk1_Ch2_01.ipynb 中 3.2.1 等差数列 直接跳到 3.2.3 二元函数，是否应为“3.2.2 二元函数”？

### ISSUE THREAD

**Issue by youhuangla** [Visualize-ML/Book1_Python-For-Beginners#44]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/71770193/5c5c0070-47f5-4977-8c88-01033b804a9c)
https://github.com/Visualize-ML/Book1_Python-For-Beginners/blob/main/Book1_Ch02_Python_Codes/Bk1_Ch2_01.ipynb 中 3.2.1 等差数列 直接跳到 3.2.3 二元函数，是否应为“3.2.2 二元函数”？

**Comment by Visualize-ML** [comment]
谢谢你，九月份将统一修改。请继续批评指正。

Cheers,
James
