### ISSUE TITLE
Bk1_Ch2_01.ipynb 序号问题

### ISSUE THREAD

**Issue by Maze-is-moon** [Visualize-ML/Book1_Python-For-Beginners#45]
老师好！
问题：1.2和1.3的序号顺序反了
谢谢老师的教程～

**Comment by Maze-is-moon** [comment]
Book_1_Ch_02__JupyterLab，用起来__编程不难__鸢尾花书__从加减乘除到机器学习.pdf
Page 7 “边际模式”是否应该为“编辑模式”？
<img width="801" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/139441233/ce29a17c-2f05-4228-b8f8-c76dc45614b5">

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。下周统一修改更新。

请继续批评。

Cheers,
James

**Comment by Maze-is-moon** [comment]
Book_1_Ch_06__Python运算,
Page 7，"加等于"前面建议换行。
<img width="927" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/139441233/f3b3e569-04c1-4dee-a43f-2ff5290c4634">

**Comment by Maze-is-moon** [comment]
Book_1_Ch_08__Python函数,
Page 4，如图，缺少字
<img width="954" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/139441233/1082976f-346c-4745-8328-f41d0e2f5457">

**Comment by Visualize-ML** [comment]
谢谢你，下一轮统一修改。请继续批评
