### ISSUE TITLE
Book_1_Ch_13__聊聊NumPy  PDF文字有误

### ISSUE THREAD

**Issue by Just-W-E** [Visualize-ML/Book1_Python-For-Beginners#46]
姜老师好！
Page 5 13.3生成数列中numpy.linspace的说明里
“例如，numpy.linspace(1, 10, 6) 生成一个等间距数列 [1, 3.25, 5.5, 7.75, 10]。”
应为“例如，numpy.linspace(1, 10, 5) 生成一个等间距数列 [1, 3.25, 5.5, 7.75, 10]。”

**Comment by Visualize-ML** [comment]
谢谢你，已经修改。请继续批评指正。

Cheers,
James

**Comment by Visualize-ML** [comment]
确实写错了。请继续批评指正。

Cheers,
James
