### ISSUE TITLE
Book_1_Ch_05__Python数据类型_page6

### ISSUE THREAD

**Issue by w741506159** [Visualize-ML/Book1_Python-For-Beginners#51]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/21236511/ded1ba0a-c0ad-4a49-9e13-04540dbe5230)
输出的结果应该是'Scikit-Learn is fun! Scikit-Learn is fun! Scikit-Learn is fun! '

**Comment by Visualize-ML** [comment]
谢谢你，下一轮修改。请继续批评指正
