### ISSUE TITLE
Book_1_Ch_15__NumPy 常见运算_page7

### ISSUE THREAD

**Issue by a-kkiri** [Visualize-ML/Book1_Python-For-Beginners#52]
[![pPpOFyt.png](https://s1.ax1x.com/2023/07/31/pPpOFyt.png)](https://imgse.com/i/pPpOFyt)
请问能否修改图中红框内表述，“沿行取得最大值” 第一感觉容易被认为是取得每一行的最大值，后面的 “沿列取得最大值” 也是同样。

**Comment by Visualize-ML** [comment]
谢谢你，确实表述不严谨。下一批上传统一更新。请继续批评指正。

Cheers,
James
