### ISSUE TITLE
Book_1_Ch_19__聊聊Pandas__Page 4

### ISSUE THREAD

**Issue by glockhilld** [Visualize-ML/Book1_Python-For-Beginners#55]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/65941568/32160f0b-ea3c-43b7-80fc-9b64216d942e)
此处有文字错误，应该为“一个”

**Comment by Visualize-ML** [comment]
谢谢你，确实错了。请继续批评指正。

Cheers
