### ISSUE TITLE
Book_1_Ch_09__Python面向对象编程

### ISSUE THREAD

**Issue by awewu** [Visualize-ML/Book1_Python-For-Beginners#59]
图3、图4、图5的代码注释有点问题
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/57051851/ccde7391-22d8-4046-a5db-6746009ee6b3)

**Comment by Visualize-ML** [comment]
谢谢你，复制粘贴忘了修改。请继续批评指正。

Cheers
