### ISSUE TITLE
Book_1_Ch_24__Pandas时间序列

### ISSUE THREAD

**Issue by undefine-man** [Visualize-ML/Book1_Python-For-Beginners#70]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/24623544/ad5cf0d7-9507-442a-840c-44d5b854dfaa)
pandas.DataFrame.xxx()

![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/24623544/4777b41b-c1a9-4a9c-82ee-fd101f384d94)
字体未统一

**Comment by Visualize-ML** [comment]
谢谢你。
天，应该改为营业日，business day
字体问题都不需要挑。出版社排版时，会处理字体。

Cheers,
James
