### ISSUE TITLE
Bk1_Ch_27_Statsmodels统计模型

### ISSUE THREAD

**Issue by hsplsp** [Visualize-ML/Book1_Python-For-Beginners#73]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/119094347/b688ac63-bfc4-4420-a715-380932d474c4)
感觉最后一行是不是应该写“本章介绍如何使用Statsmodels中几个常见函数”而不是SciPy的常见函数orz

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。下一批次统一上传。请继续批评。

Cheers,
James
