### ISSUE TITLE
Book_1_Ch_19__聊聊Pandas中的一个小bug

### ISSUE THREAD

**Issue by Cathelloya** [Visualize-ML/Book1_Python-For-Beginners#75]
在第6页的位置，np_array的名字变成了numpy_array,因此出现了NameError

![7a22d5b176a67925df6680cfe86ebf78](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/88889925/948a9b05-b4d1-44a6-952a-0d162a730f07)

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。请继续批评指正。

Cheers,
