### ISSUE TITLE
Book_1_Ch_10__聊聊可视化_page14

### ISSUE THREAD

**Issue by flytianwen** [Visualize-ML/Book1_Python-For-Beginners#76]
如果我们图5所示-->如我们图15所示
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/39915148/d350a5bc-251c-4e15-88e6-2c9dcaece304)

**Comment by Visualize-ML** [comment]
谢谢你，文字确实错误。下一轮统一上传修改。请继续批评。

Cheers,
James
