### ISSUE TITLE
ch10-图 17 勘误

### ISSUE THREAD

**Issue by wxhnewStar** [Visualize-ML/Book1_Python-For-Beginners#81]
生姜老师,如题,ch10 中图 17 的左上子图,坐标展示出错了.
正负 y 轴坐标标反了位置.
(by the way, 今天刚拿到了您的 3 和 4 新书,印刷质量特别好! 可惜没抽到有签名的哈哈)

**Comment by Visualize-ML** [comment]
谢谢你！咱们有好评、致学、纠错，赠书活动，可以在京东 + 豆瓣写好评，发我截图，我转给出版社，下一本上架前，就可以免费拿样书 和签名卡。

或者纠错，根据纠错数量，前10名也一样奖励。

好评最容易了。

Cheers

**Comment by wxhnewStar** [comment]
好!
好评截图发给您,是通过邮箱吗?  还是 b 站私信? 
需要附上我的联系方式这些吗?

> 2023年9月25日 21:30，Iris Series: Visualize Math -- From Arithmetic Basics to Machine Learning ***@***.***> 写道：
> 
>

**Comment by Visualize-ML** [comment]
谢谢！回复邮件就行，豆瓣和京东，截图。不吹不黑哈，都是读者真是评价，没水军...
