### ISSUE TITLE
chapter 03 表 2. JupyterLab 中常用魔法命令  %lsmagic 和%magic 分别重复了两次

### ISSUE THREAD

**Issue by zehaochan** [Visualize-ML/Book1_Python-For-Beginners#82]
chapter 03 表 2. JupyterLab 中常用魔法命令  %lsmagic 和%magic 分别重复了两次
<img width="720" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/130197613/205f7f4c-11ef-46cd-a430-04e734e5d321">

**Comment by Visualize-ML** [comment]
谢谢你，确实重复了。下一轮统一上传修改，请继续批评指正。

中秋快乐！
