### ISSUE TITLE
chapter 10 .1 语句错误

### ISSUE THREAD

**Issue by zehaochan** [Visualize-ML/Book1_Python-For-Beginners#83]
<img width="1208" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/130197613/98a3c3fa-b793-4489-a271-42edeb025c0d">

**Comment by Visualize-ML** [comment]
这一句还真没错，就是有点别嘴。请继续批评指正。

中秋快乐！
