### ISSUE TITLE
Ch_06 图21

### ISSUE THREAD

**Issue by 94mu** [Visualize-ML/Book1_Python-For-Beginners#84]
图21中原始代码是：
plt.axvline(mean_loc + mean_loc, color = 'pink', label='Mean ± std')
plt.axvline(mean_loc - mean_loc, color = 'pink')

我的理解是这两行代码中后一个"mean_loc" 是不是应该改成 “std_loc”?

94mu

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。请继续批评指正。

中秋快乐！
