### ISSUE TITLE
book_1_ch_10 图17. 单位圆原理 左上角的sin曲线y轴刻度出错

### ISSUE THREAD

**Issue by zehaochan** [Visualize-ML/Book1_Python-For-Beginners#85]
book_1_ch_10 图17. 单位圆原理 左上角的sin曲线y轴刻度出错
<img width="577" alt="image" src="https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/130197613/0eade11a-1744-4745-97f9-162454d64b27">

**Comment by Visualize-ML** [comment]
谢谢你，确实写错了。这部分内容已经移到了《可视之美》。请继续批评指正。

中秋快乐！
