### ISSUE TITLE
2.4 查看python库版本号

### ISSUE THREAD

**Issue by l1399348397** [Visualize-ML/Book1_Python-For-Beginners#88]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/64197373/625fc573-24a4-4909-8b13-add18248024f)
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/64197373/b0d4638e-de65-46d9-a69f-55e0e6443b03)

绿色三角或许可以改成绿色播放图标，小问题不影响阅读

**Comment by Visualize-ML** [comment]
已经修改，谢谢你。请继续批评指正。
