### ISSUE TITLE
Ch5 python 数据类型 |5.3 字符串|表 2. 常用.format() 示例

### ISSUE THREAD

**Issue by l1399348397** [Visualize-ML/Book1_Python-For-Beginners#89]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/64197373/8aa6c743-81d5-4fb8-b060-904948e419ba)
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/64197373/62b50e24-7c89-40da-a348-ba76e6034069)
’#‘ 号后跟的是结果的意思把

**Comment by Visualize-ML** [comment]
已经修改，请继续批评指正。谢谢
