### ISSUE TITLE
Ch5 python 数据类型 |5.4 列表 |图15. 列表常用方法、操作

### ISSUE THREAD

**Issue by l1399348397** [Visualize-ML/Book1_Python-For-Beginners#91]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/64197373/10779563-3cef-41b6-9296-5ad1274b7c7a)
将列表用所有字符连接，连接符为下划线_
是不是应该改成：
将列表所有字符用连接符连接，连接符为下划线_

**Comment by Visualize-ML** [comment]
请问具体问题是什么？

**Comment by Visualize-ML** [comment]
已经修改，情继续指正批评。
