### ISSUE TITLE
Page 22| CH5  |  集合

### ISSUE THREAD

**Issue by l1399348397** [Visualize-ML/Book1_Python-For-Beginners#93]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/64197373/9f366b69-ac00-478a-83cb-f28af2f222df)
一点点小建议，首先我是0基础来学的
在使用add（）和update（）来添加元素时，发现add函数可以添加 int、bool、str类型，同时添加bool类型时，打印后并不显示，而update函数只能添加列表、str，同时添加str时会被拆分成单个字符
或许书中增加一下函数可以处理的数据类型，可以更方便小白入门？
我不知道这些在计算机领域是不是一个默认的规则，或者您觉得这样写太啰嗦了反而不利于入门

**Comment by Visualize-ML** [comment]
谢谢你，确实这样。Python语法很灵活，我们不可能面面俱到。非常高兴你能自主探索。
