### ISSUE TITLE
Book1_ch15 对应的 jupyter notebook 中一段内容有误

### ISSUE THREAD

**Issue by wxhnewStar** [Visualize-ML/Book1_Python-For-Beginners#95]
IN[68] 中:

"
# 查看原始数组
print(a) # 输出：[1 0 3 4 5]
"
备注里对 a 的输出值写错了,应该是 "[1 1000 3 4 5]"

**Comment by Visualize-ML** [comment]
谢谢你，哪一章？哪个代码文件？

**Comment by wxhnewStar** [comment]
抱歉! 标题打错了, 是 14 章唯一的那个 notebook,第 68 个格子中,对应部分出错了

**Comment by Visualize-ML** [comment]
谢谢你！录制微课视频时，会上传修改后版本。请继续批评指正。
