### ISSUE TITLE
Page 21 | Chapter 6 Python 常见运算

### ISSUE THREAD

**Issue by l1399348397** [Visualize-ML/Book1_Python-For-Beginners#97]
![image](https://github.com/Visualize-ML/Book1_Python-For-Beginners/assets/64197373/1022ff19-1bd6-4b2a-a6c1-b2144e5e0eb8)
前面说0为天蓝色，1为粉紫色，但是图上几乎都挡住了，这样打印出来就更看不清了吧，感觉可以优化一下

**Comment by Visualize-ML** [comment]
谢谢你，确实。会在排版时优化。请继续批评指正。
