### ISSUE TITLE
Book_1_Ch_03__JupyterLab修改建议

### ISSUE THREAD

**Issue by dalianshiyi** [Visualize-ML/Book1_Python-For-Beginners#99]
Book_1_Ch_03__JupyterLab，用起来__编程不难__鸢尾花书__从加减乘除到机器学习|表5 键盘上常用按键中英文名称|修改建议1.重音符（grave accent）| 修改建议2.左圆括号和右圆括号 单词拼写错误 应为 parentheses

**Comment by Visualize-ML** [comment]
谢谢你，这个Issue先开着，我会在排版稿上修改。请继续批评指正。

**Comment by SodaWang** [comment]
2.2.3 鸢尾花矩阵的行向量与列向量表述应该是写反了
原文是
鸢尾花数据的前四列可以写成矩阵 $X$。  
矩阵 $X$ 有150行4列，因此 $X$ 的形状为 $150 \times 4$。
$X$ 可以写成一组列向量：
$$X = \begin{bmatrix}x_1, x_2, x_3, x_4 \end{bmatrix}$$
每个列向量代表鸢尾花量化特征的样本值，比如$x_1$代表花萼长度的150个样本值。
同时，$X$ 还可以写成一组行向量：
$$X = \begin{bmatrix}x^{(1)}\\
                     x^{(2)}\\ 
                     x^{(3)}\\
                     \vdots \\
                     x^{(150)} 
      \end{bmatrix}$$
每个行向量代表一朵鸢尾花的花萼长度、花萼宽度、花瓣长度和花瓣宽度值，比如$x^{(1)}$ 代表编号为1的鸢尾花。

应该是 

鸢尾花数据的前四列可以写成矩阵 $X$。  
矩阵 $X$ 有150行4列，因此 $X$ 的形状为 $150 \times 4$。
$X$ 可以写成一组行向量：
$$X = \begin{bmatrix}x_1, x_2, x_3, x_4 \end{bmatrix}$$
每个列向量代表鸢尾花量化特征的样本值，比如$x_1$代表花萼长度的150个样本值。
同时，$X$ 还可以写成一组列向量：
$$X = \begin{bmatrix}x^{(1)}\\
                     x^{(2)}\\ 
                     x^{(3)}\\
                     \vdots \\
                     x^{(150)} 
      \end{bmatrix}$$
每个行向量代表一朵鸢尾花的花萼长度、花萼宽度、花瓣长度和花瓣宽度值，比如$x^{(1)}$ 代表编号为1的鸢尾花。

**Comment by Visualize-ML** [comment]
谢谢你。

鸢尾花数据集，有150朵花 (行)，4个量化特征 (列)。

https://en.wikipedia.org/wiki/Iris_flower_data_set
